version: '3.3'

services:
  idporten-innlogging-statistikk-klient:
    image: ${REGISTRY}/idporten-innlogging-statistikk-klient:${VERSION}
    ports:
      - "8085:8080"
    configs:
      - source: idporten-innlogging-statistikk-klient
        target: /application.properties
    secrets:
      - source: idporten-innlogging-statistikk-klient_ingest-password
        target: idporten-innlogging-stat-pumba
    networks:
      - statistics

networks:
  statistics:
    external: true

secrets:
  idporten-innlogging-statistikk-klient_ingest-password:
    external: true

configs:
  idporten-innlogging-statistikk-klient:
    external: true
