version: '3.3'

services:
  idporten-innlogging-statistikk-klient:
    image: difi/idporten-innlogging-statistikk-klient:${VERSION}
    ports:
      - "8085:8080"
    configs:
      - source: idporten-innlogging-statistikk-klient
        target: /application.properties
    networks:
      - statistics

networks:
  statistics:
    external: true
